language: node_js
node_js:
- '8'
before_install:
- npm i -g yarn@latest
install:
- yarn install
script:
- yarn lint
- yarn test:coverage
after_success:
- yarn report:coveralls
cache: yarn
deploy:
  provider: npm
  email: ammmze@gmail.com
  api_key:
    secure: tiEc/ZUFJf9tBb/bQUUIXJAjwI5mFM3KViTFqS7hByK51C1ydIQE7gdYBdgm7pVw0I8ajmwozw94CGnYjuJivdTPtaKhnN9NHjZw25OygXds/UzsUshFzaN90qL4+8M5DKW0JiZNaVtKQT1cSU+6aNXFa7ojY0pKajdtNrweL9SQaumY+7gUcYdc6Lz2K2/LylqAPGQ63mXvhKB+pVQXTQE0/P1JvQa6Z8Q12qJOBgyda/EmIUC3baAG2ECBJDc6Aax6YOwFo74cGtXk/9+fv9lIIax6u0V9gYXa5D6j2GzW5sVzrDe8PkQMIKHcHblrJgdsyiQ2Cc/+fghF+Qnv+wHpTyGSkCPqmc4G/pinmqSznsxpr7fNAOINSlr0NmkFHEXPtDpXs9+GwuDeIY9N67YeOZMjIQ2ASq22pTK9uILv4xgsz/3s1xxrZU8c13ZVQRCRJlvuKqvSuptmiZTyAEMDcdHJoT8mwH9PutrWlB9hCvYG6jY9ma78tZElX8NWIyKOTIYGtbTNsuIiptncRpRxBLyDyljW8UakuHIWO1dS2w8eLsa02h+ZxgnELHptBo68CcwLCNhytrhCOBcHhPk+YJa5sRQ6OqpU1pBNWFugg534h5HsMXBjWgx+AmlnjiE1jF5hc1lSfay6PLbjbhF4G1cmErB0YWphKftAFuc=
  on:
    tags: true
    repo: MashupMill/sync-pom-version-to-package
