language: node_js
node_js:
  - '6'
before_install:
  - npm i -g npm@latest
install:
  - yarn install
script:
  - yarn lint
  - yarn test:coverage
after_success:
  - yarn report:coveralls
cache: yarn
deploy:
  provider: npm
  email: ammmze@gmail.com
  api_key:
    secure: k/R7pRamhc6nzHrXhBwptrVJmZfEYrby/80KrMfwIkpwyg6wnKNFIHndSlQraDug05fzF/CN9tkxNdw9ROfZtzJnYoHfg5ZoDeESymNj0aXDRyD07sCgBalNO0o5OjeDM8o0/52Og8TFIJAPzTsXlyJz4PVm8raa/26rlpYPG1shaq6XupwzAv5i+6LWGwmDrbU8uofSCJYYQEP4pJSNgJLR7DT0OFc//DbP7JIiEt15ECqPI7Ky/winLZ2WKPc/seIdhb4uJD0z4JCstlgUifh5TNi1v7rsmeTqv5uiB64yL/8btEb3TRii9RP3q5sno/WmtoMzbbcUuhIxC4xJ67URAzMt8U5NtAhhB7qfH41u0wwDwBdSVcufXSgj6MJQc00aYbINUYcorRhUoc0wrAQ7xrkCaivMRTZmDXjgbAsQSTRa0logDrKZHn9sIgqMKlhw6HBIUEUFRarwJo17VT1gbg52mhePmGmkNoSyrGSwh5V+JbMoe8MvpWe95MeXy5fe6c+ekEPONVRHeurHgv9r96xS5+pLJkCc58vZLlmij9JMerr7YNuqJ5wpwjr44ss9mqupc9ucouEA9YrrNr0NBXXYdhXtuf1shRhNDCuWy+fpzYU+r5ft5YgHkBTt+zIn/31aA+wAmgV/AmDzCVrmcipWZjl6Qo0CrV3PZ2Q=
  on:
    tags: true
    repo: MashupMill/sync-pom-version-to-package
